import { Button } from "std-widgets.slint";
import { CustomButton } from "custom-widgets/custom-button.slint";

export component FsEntry {
    in property <string> name;
    // TODO: What type of entry is it?

    CustomButton {
        width: 100%;
        height: 80%;

        background: transparent;
        border: black;
        border_width: 1px;

        on_click => {
            debug("Clicked fs entry.")
        }
    }
    Text {
        width: 100%;
        height: 20%;

        font-size: parent.width / 10;

        x: 0;
        y: parent.height;

        text: name;
        overflow: elide;
    }
}