import { FsEntry } from "components/fs-entry.slint";
import { Theme } from "theme.slint";
import { FsEntryData } from "structs/fs-entry-data.slint";
import { FilesBox } from "components/files-box.slint";

export { FsEntryData, FilesBox }

export component MainWindow inherits Window {
    callback fs_entry_clicked(FsEntryData);

    preferred-height: 540px;
    preferred-width: 600px;

    FilesBox {
        fs_entry_clicked(entry_clicked) => {
            fs_entry_clicked(entry_clicked)
        }
    }
}